config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :questions
  resources :services do
    collection do
      post :requested
    end
    member do
      get :execute
      get :result
    end
  end
  resources :answers, only: :create

  get '/finished', to: 'process#finished'
  get '/:external_code', to: 'process#index'
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  before_create :define_status

  has_many :answers

  def already_answered?
    answers.any?
  end

  def result_data
    total_questions = Question.count
    right_answers = answers.select(&:corret?).size
    {
      score: (right_answers * 100) / total_questions,
      summary: 'Avaliação Comportamental',
      link: 'https://trabalheconosco.vagas.com.br/vagas',
      completionDate: created_at.strftime("%Y-%m-%d"),
      expires_at: (created_at + 1.year).strftime("%Y-%m-%d")
    }
  end

  def send_message
    ExternalService.send_message(self)
  end

  def send_result
    ExternalService.send_result(self)
  end

  private

  def define_status
    self.status = :created
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy execute result]
  skip_before_action :verify_authenticity_token, only: :requested

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show; end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit; end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to services_url, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /services/requested
  # POST /services/requested.json
  def requested
    requested_params = {
      external_code: params[:id],
      company_id: params[:company][:id],
      company_name: params[:company][:name],
      recruiter_id: params[:recruiter][:id],
      recruiter_name: params[:recruiter][:name],
      applicant_id: params[:applicant][:id],
      applicant_name: params[:applicant][:name],
      job_id: params[:job][:id],
      job_title: params[:job][:title],
      status: params[:status]
    }

    @service = Service.new(requested_params)

    if @service.save
      render json: { status: :created }, status: :created
    else
      render json: @service.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to services_url, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /services/1/execute
  def execute
    @service.send_message
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully executed.' }
      format.json { head :no_content }
    end
  end

  # GET /services/1/result
  def result
    @service.send_result
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service result was successfully sent.' }
      format.json { head :no_content }
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:external_code,
                                    :company_name,
                                    :recruiter_name,
                                    :applicant_name,
                                    :job_id,
                                    :job_title)
  end
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='form-body'>
    <p>
      <%= form.label :external_code, 'External code' %>
      <%= form.text_field :external_code %>
    </p>
    <p>
      <%= form.label :company_name, 'Company Name' %>
      <%= form.text_field :company_name %>
    </p>
    <p>
      <%= form.label :recruiter_name, 'Recruiter name' %>
      <%= form.text_field :recruiter_name %>
    </p>
    <p>
      <%= form.label :applicant_name, 'Applicant name' %>
      <%= form.text_field :applicant_name %>
    </p>
    <p>
      <%= form.label :job_id, 'Job ID' %>
      <%= form.text_field :job_id %>
    </p>
    <p>
      <%= form.label :job_title, 'Job title' %>
      <%= form.text_field :job_title %>
    </p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>External code</th>
      <th>Company Name</th>
      <th>Recruiter name</th>
      <th>Applicant name</th>
      <th>Job ID</th>
      <th>Job title</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td> <%= service.external_code %> </td>
        <td> (<%= service.company_id %>) <%= service.company_name %> </td>
        <td> (<%= service.recruiter_id %>) <%= service.recruiter_name %> </td>
        <td> (<%= service.applicant_id %>) <%= service.applicant_name %> </td>
        <td> <%= service.job_id %> </td>
        <td> <%= service.job_title %> </td>
        <td> <%= service.status %> </td>
        <td>
          <%= link_to 'Execute', "#{service_path(service)}/execute" %>
          <% if service.already_answered? %>
          | <%= link_to 'Send Result', "#{service_path(service)}/result" %>
          <% end %>
          | <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>